# Generated by Django 5.0.4 on 2024-04-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='especialidades',
            new_name='especialidade',
        ),
    ]
