# Generated by Django 5.0.4 on 2024-04-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_datasabertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidades'),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
